- hosts: all
  tasks:
  - name: Create registry path TLS 1.1\Server
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server

  - name: Add or update registry path TLS 1.1\Server, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path TLS 1.1\Server, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Create registry path TLS 1.1\Client
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client

  - name: Add or update registry path TLS 1.1\Client, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path TLS 1.1\Client, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Create registry path TLS 1.0\Server
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server

  - name: Add or update registry path TLS 1.0\Server, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path TLS 1.0\Server, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Create registry path TLS 1.0\Client
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client

  - name: Add or update registry path TLS 1.0\Client, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path TLS 1.0\Client, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Create registry path SSL 3.0\Server
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server

  - name: Add or update registry path SSL 3.0\Server, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path SSL 3.0\Server, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Create registry path SSL 3.0\Client
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client

  - name: Add or update registry path SSL 3.0\Client, with entry 'Enabled', and containing '0'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
      name: Enabled
      data: 0
      type: dword

  - name: Add or update registry path SSL 3.0\Client, with entry 'DisabledByDefault', and containing '1'
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
      name: DisabledByDefault
      data: 1
      type: dword

  - name: Add or update registry path Microsoft\.NETFramework\v2.0.50727, with entry 'SchUseStrongCrypto', and containing '1'
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v2.0.50727
      name: SchUseStrongCrypto
      data: 1
      type: dword

  - name: Add or update registry path Microsoft\.NETFramework\v4.0.30319, with entry 'SchUseStrongCrypto', and containing '1'
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      data: 1
      type: dword

  - name: Add or update registry path Wow6432Node\Microsof\.NETFramework\v2.0.50727, with entry 'SchUseStrongCrypto', and containing '1'
    win_regedit:
      path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v2.0.50727
      name: SchUseStrongCrypto
      data: 1
      type: dword

  - name: Add or update registry path Wow6432Node\Microsof\.NETFramework\v4.0.30319, with entry 'SchUseStrongCrypto', and containing '1'
    win_regedit:
      path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      data: 1
      type: dword
