- name: Create Azure Win VM
  hosts: all
  connection: local
  vars:
    resource_group: ansible-win-rg
    location: southeastasia
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: vNet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: ansibleSubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: vNet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: ansiblePublicIP
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Artifact Public IP to Tower Workflows
      set_stats:
        data:
          newVMIP: "{{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: networkSecurityGroup
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range: 
              - 5985
              - 5986
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Create a network interface
      azure_rm_networkinterface:
        name: ansibleNic
        resource_group: "{{ resource_group }}"
        virtual_network: vNet
        subnet_name: ansibleSubnet
        security_group: networkSecurityGroup
        ip_configurations:
          - name: default
            public_ip_address_name: ansiblePublicIP
            primary: True


    - name: Create VM By Using Company Image
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vmname }}"
        vm_size: Standard_DS1_v2
        admin_username: sysadmin
        admin_password: P@ssw0rd123456
        network_interfaces: ansibleNic
        tags: Project=Ansible
        os_type: Windows
        image:
          name: AnsibleVM-Master-image
          resource_group: "{{ resource_group }}"
      when: vmtype == "Company Image"

    - name: Create VM By Using Azure Marketplace Image
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vmname }}"
        vm_size: Standard_DS1_v2
        admin_username: sysadmin
        admin_password: P@ssw0rd123456
        network_interfaces: ansibleNic
        tags: Project=Ansible
        os_type: Windows
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
      when: vmtype == "Azure Marketplace Image"


    - name: create Azure vm extension to enable HTTPS WinRM listener
      azure_rm_virtualmachine_extension:
        name: winrm-extension
        resource_group: "{{ resource_group }}"
        virtual_machine_name: "{{ vmname }}"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: 1.9
        settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
        auto_upgrade_minor_version: true

    - name: wait for the WinRM port to come online
      wait_for:
        port: 5986
        host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
        timeout: 600
