- name: Remove tower host
  hosts: all
  connection: local
  tasks:
  - name: Remove tower host
    tower_host:
      name: "{{ newVMIP }}"
      description: "Local Host Group"
      inventory: "WORKFLOW"
      state: absent
      tower_config_file: "~/tower_cli.cfg"
